### ISSUE TITLE
Implement Field of View and Explored Tiles

### ISSUE THREAD

**Issue by fcheadle** [thesadrogue/TheSadRogue.Integration#10]
As a roguelike developer, I would like for the map that comes from my integration library to contain a Field-Of-View handler that takes care of tile visibility and seen/unseen values.

**Comment by Chris3606** [comment]
@Thraka  This will likely require integrating bugfixes made to SadConsole v9 _after_ the release of 9.0.0-beta3, so this will probably have to wait until the next SadConsole release.

@fcheadle An implementation of this may also be affected by the architectural fixes for #4, #9, and #16 , so these may be good prerequisites.
