### ISSUE TITLE
RogulikeMap Cannot be Rendered by more than 1 screen surface simulaneously

### ISSUE THREAD

**Issue by Chris3606** [thesadrogue/TheSadRogue.Integration#16]
The current implementation of simply exposing an `EntityRenderer` property doesn't work generally, because a `Renderer` can only be attached to one surface; a more complex approach is necessary for this use case.  One such approach is demonstrated [here](https://github.com/Chris3606/TheSadRogue.Integration/blob/more-feature-dev/TheSadRogue.Integration/RoguelikeMap.cs#L158)

**Comment by fcheadle** [comment]
I've copied the code from the link you posted. Seems to work well enough.

**Comment by Chris3606** [comment]
Should be solved in most recent PR.
