### ISSUE TITLE
Component System Allows Bad States and Performs Poorly

### ISSUE THREAD

**Issue by Chris3606** [thesadrogue/TheSadRogue.Integration#17]
Per initial PR review of the #1 :

# Component System
When I look at the code, a few things stand out to me as undesirable in the current "universal component" system and the corresponding forwarder functions on `RoguelikeEntity`.

## Arbitrary Dependence on IRoguelikeComponent
The dependence on `IRoguelikeComponent` feels arbitrary; it's a blank interface that specifies two other interfaces.  Since there's no functionality defined in that interface, functionally something that implements `IRoguelikeComponent` should be equivalent to something that implements `IGameObjectComponent` and SadConsole's `IComponent`; yet because of the type structure the library treats them differently.  A few different ways I've come up with to get into frustrating/sticky situations due to this:
```CSharp
class MyClass : IRogueLikeComponent { /* do useful things */ }
class MyClass2 : SadConsole.Components.IComponent, IGameObjectComponent { /* do useful things */ }
var c1 = new MyClass(...);
var c2 = new MyClass2(...);

var obj = new RogueLikeEntity(...)
obj.AddComponent(c1); // Works

// Works but Update-based stuff from SadConsole magically doesn't
obj.GoRogueComponents.Add(c1);
// Works, but GoRogue's component list loses it
obj.SadComponents.Add(c1);

// Compiler error (c2 doesn't implement IRoguelikeComponent)
obj.AddComponent(c2);
```

Obviously this type of code could be frustrating to debug; particularly if `AddComponent` is not accessible in a certain context if you have an object casted to `IGameObject` or `SadConsole.Entities.Entity`.

I think it should be possible to depend on precisely the two interfaces required without creating an arbitrary third (see proposal at bottom).

## Non-Obvious Performance Implications
A key difference in `SadComponents` vs `GoRogueComponents` is the performance tradeoffs for calling certain functions.  The performance tradeoffs come from optimizations for different use cases.  The performance differences on their own can be significant, but adding to the complexity and obfuscation created by the current implementation is that the wrapper functions on `RoguelikeEntity` generally get the worst of either world, and sometimes end up with performance _worse_ than either of the other lists.  An example:

- `GoRogueComponents.GetFirst<T>()`
    - Efficiency: O(1) (a single dictionary access)
- `SadComponents.GetFirst<T>()`
    - Doesn't really exist; the closest thing is iterate through all components and try to cast, taking the first one that succeeds
    - O(n) efficiency (where n is total number of components)
- `RoguelikeEntity.GetComponent`
    - Requires calling `RoguelikeEntity.GetComponents()`
    - `O(n) + O(t)` in its current implementation
        - where `n` is total number of components, `t` total components of type T

It's possible to optimize this a little, but the maximum extent to which it can be optimized is to the worst case of the equivalent `GoRogueComponents` and `SadComponents` operations.  For most operations, that amounts to `O(n)`; and in a typical use case it may end up being more than that because all components are stored in both lists if all the components implement `IRoguelikeComponent`.

## Suggestions/Discussion
I understand the desire to have a single function for any component, but inevitably since the lists have different performance parameters, it's extremely difficult to optimize such operations; and worse, to people that aren't familiar with the code, the performance differences would be subtle.  This is made even harder to implement because `GameObjects` must support components with tags, whereas `SadConsole.ScreenObjects` do not.

### Idea 1: Type Restrictions on Components
One option that would help with some issues is to restrict the types of components allowed to be placed on `RogueLikeEntity`.  Specifically, one would need to mandate that they all implement `IRogueLikeEntity`, or at least that they all implement both `IGameObjectComponent` and `SadConsole.Components.IComponent`.  This is simple to do with an event handler for component added; simply try to cast it when it is added and if it will not cast, throw an exception.

This restriction allows you to be certain that all components are in both lists; so functions become much easier to implement because you can only consider a single list for retrievals.

The downside to this is that it may have performance implications during the update loop, particularly when a user is not careful to turn off all functionality (Update, UsesKeyboard, etc) that SadConsole provides when they don't require it.  Additionally, in some cases it requires you to implement many fields that you don't necessarily need.

This also doesn't really help the first case above, where undesirable cases can still occur.

### Idea 2: Remove Forwarders and Focus on Preventing Potential for Desyncs
Another option is to forgo forwarding functions entirely, and instead focus on preventing desyncs in the first place.  A relatively simple approach for this would be to remove `IRogueLikeEntity`, then create event handlers for `SadComponents` and `GoRogueComponents` something to this effect:
```CSharp
public void SadComponents_Added(object s, Args e)
{
    if (!GoRogueComponents.Contains(e.Item))
        GoRogueComponents.Add(e.Item);
}

public void GoRogueComponents_Added(object s, Args e)
{
    if (e.Item is SadConsole.Components.IComponent c && !SadComponents.Contains(c))
        SadComponents.Add(c);
}
```

Depending on the implementation of those events, care may (or may not) need to be taken to avoid infinite recursion, however an event structure like this would ensure that anything that can be added as a component is, regardless of whether you call `GoRogueComponents.Add` or `SadComponents.Add`. 

The user can then use `GoRogueComponents` as a universal component list that is guaranteed to contain all components, and perhaps this could even be enhanced with something like:
```CSharp
    public ITaggableComponentCollection Components => GoRogueComponents;
```

There are other approaches as well; at minimum combining the two above; but these were some thoughts I had looking at it.

**Comment by Chris3606** [comment]
From Thraka:

> Would it be helpful to add a protected virtual method on ScreenObject that is called when a SadComponent is removed/added? This way you can do things like check for a specific interface and automatically add it the GoRogue component list?

**Comment by Chris3606** [comment]
From fcheadle:
In Homicide Detective, I had to work around a constraint to get my wind-blowing animation onto grass tiles. It may be beneficial to allow users to purposefully de-sync the two collections.

I hink I'm starting to agree with you about components. Here is another thought I'm having:

## Remove IRogueLikeComponent

Remove IRogueLikeComponent. Make my specific components (for example, PlayerControlsComponent) inherit from SadConsole.Component and Implement IGameObjectComponent.

Change all my Add/Has/Get/Remove etc function to be like so:

```
public void AddComponent(object component, string tag = "")
{
    if(component is SadComponent sc)
        SadComponents.Add(sc);
    if(component is IGameObjectComponent goc)
        AddGoRogueComponent(goc);
}
```

> Would it be helpful to add a protected virtual method on ScreenObject that is called when a SadComponent is removed/added?

I don't think so, because `SadComponents` is already an `ObservableCollection` and I can hook events to do that easily enough at the moment.

**Comment by Chris3606** [comment]
Yes, this is a variation of my idea 2; really more less a combination of elements from both idea 2 and idea 1. My only immediate issue with this is that keep in mind, any object, not just ones implementing IGameObjectComponent, are allowed to be placed on GoRogue GameObjects. Additionally, as a minor detail, keep in mind that "" is not equivalent to null when used as a tag in GoRogue's component system; the default should be null for no particular tag. So if you wanted to pursue this option, I'd suggest the following amendment: remove IRogueLikeComponent, and write your functions like so:

public void AddComponent(object component, string? tag = null)
{
    if(component is SadConsole.Components.IComponent sc)
        SadComponents.Add(sc);

    // Add any and all components regardless of type to GoRogue's list
    GoRogueComponents.Add(goc, tag);
}
It would even be possible to potentially implement the event handlers from Idea 2 in my initial post, to ensure that even if someone calls GoRogueComponents.Add or SadComponents.Add directly, no desyncs are created. That functionality could even be turned on/off by an optional flag if someone really, really wants to have something that is only in SadConsole's list.

I think the biggest difference between this and Idea 2 in the initial post, is this implements the synchronized add functionality explicitly as helper functions on the entity class, whereas Idea 2 exposes that functionality only via a Components property. You could make an argument that the Components property is more idiomatic, as component "collections" for components is the convention that both SadConsole and GoRogue use; but the difference may also serve to indicate to a user that the helpers are independent of either collection itself, so I'm not sure I have a strong preference here. @Thraka , thoughts?

One additional caveat, I'd recommend checking for `SadConsole.Components.IComponent` (as my code above does) instead of the base class, as the base class implements that interface and it makes it maximally compatible.

**Comment by Thraka** [comment]
Why not guide people to use `GoRogueComponent` only? For example, don't have `GoRogueComponent` implement the SadConsole `IComponent` interface. If someone wants to make a component that *can* be integrated into SadConsole objects, they can implement `IComponent`. Then, the `GoRogueComponent` collection can check on add/remove if the component implements `IComponent` and send it to the SadComponents.

If someone goes the extra mile of adding `IComponent` to the `GoRogueComponent`, they just need to be aware they need to continue to use the `GoRogueComponentCollection` instead of the `SadComponent` collection.

**Comment by Chris3606** [comment]
@Thraka there might be something to that; really `SadComponents` is absolutely great at being a caching structure that SadConsole uses internally to iterate really, really fast.  But for most cases that a user will use if they're going the route of `Combatant` components and things like we've done in examples (where the user themselves is not grabbing things every frame), the GoRogue component system is probably the more intended one for the use case anyway.

I think my Idea 2 was sort of similar, it just tried to make it two-way; eg make `GoRogueComponents` automatically check and add to `SadComponents`, and vice versa as well, which is a bit more complicated.  Maybe just documenting "when using `RoguelikeEntity`, use `GoRogueComponents` and SadConsole stuff will just work no matter what" is the better option.   I have some reservations about trying to create functions specifically like `AddComponent` on the entity class itself, in that when you look at the interface, it creates a little ambiguity as to what you should be using and what is equivalent to what.

**Comment by fcheadle** [comment]
Here's my proposed path forward based on these discussions:

1. Have a property, `Components`, that forwards to `GoRogueComponents`.
2. Continue using `GoRogueComponents` as the source of truth, a master list of all components on an entity. GoRogueComponents, however, are not iterated over during a typical cycle. 
3. Treat `SadComponents` as a subset `GoRogueComponents`, where only components which implement `IComponent` are stored. `SadComponents` then work according to SadConsole's rules.
4. Remove `RogueLikeComponentBase` and change `PlayerControlsComponent` to inherit from `SadConsole.Components.Component` and implement `IGameObjectComponent`
5. Each new component in the ExampleGame will implement `IGameObject`, but only some will inherit from `SadConsole.Components.Component`, depending on the needs. This should serve as a waypost for new users to determine when to use GoRogueComponents (always) and when to use SadComponents(always)
6. Keep `AddComponent` and `GetComponent` and so forth, using `GoRogueComponents` as the source of truth.

**Comment by Thraka** [comment]
> Here's my proposed path forward based on these discussions:
> 
> 1. Have a property, `Components`, that forwards to `GoRogueComponents`.

What would be the benefit of having `Components` if there are the `Add/Get` methods?

> 2. Continue using `GoRogueComponents` as the source of truth, a master list of all components on an entity. GoRogueComponents, however, are not iterated over during a typical cycle.
> 3. Treat `SadComponents` as a subset `GoRogueComponents`, where only components which implement `IComponent` are stored. `SadComponents` then work according to SadConsole's rules.
> 4. Remove `RogueLikeComponentBase` and change `PlayerControlsComponent` to inherit from `SadConsole.Components.Component` and implement `IGameObjectComponent`
> 5. Each new component in the ExampleGame will implement `IGameObject`, but only some will inherit from `SadConsole.Components.Component`, depending on the needs. This should serve as a waypost for new users to determine when to use GoRogueComponents (always) and when to use SadComponents(always)
> 6. Keep `AddComponent` and `GetComponent` and so forth, using `GoRogueComponents` as the source of truth.

**Comment by fcheadle** [comment]
That's a fair point, I can't really think of one other than some clarity for the user (Attempting to access all components via `Components` versus `GoRogueComponents`).

**Comment by fcheadle** [comment]
I've lightly switched this out on a new commit. The system works as described in my earlier comment, except that there is no `Components` property.

**Comment by Chris3606** [comment]
@Thraka @fcheadle  I actually prefer to ditch `AddComponent`, etc, and exclusively depend on the `Components` property; this is simply to keep the functionality architecturally consistent with GoRogue and SadConsole; both GoRogue and SadConsole store components on a property, so following suit with the interface exposed would seem to make more sense to me.

In any case, I agree that we most certainly should not have both `AddComponent` and such functionality _and_ `Components`; it should be one or the other.

**Comment by Chris3606** [comment]
One other point in a case for using only `Components` functions is that we ran into issues with the type-restrictions that GoRogue places on components (reference types only); we wouldn't have to tediously match non-trivial nullability and type constraints for the helper functions if we simply use what is already existing.

One potential downside to using only `Components` is that `Components` might not immediately stand out among `GoRogueComponents` and `SadComponents` as well as functions on the entity itself might.  But I think that's a matter of perspective, and maybe only a matter of choosing a better name for the property if we were to create it; maybe `AllComponents`.  In any case it's something that we do need to rely on documentation for.

**Comment by Thraka** [comment]
If the components are gorogue based and _only_ become sadconsole based when they implement the interface, then that means someone is making the component and we could just tell them that they would add the same component to both collections in that case.

**Comment by Chris3606** [comment]
I'm not sure I follow.... The whole point in providing a linked interface is to prevent the user from causing desyncs by forgetting to do this.

**Comment by fcheadle** [comment]
We could have `Components` or `AllComponents` like you say, would it be possible to use the `Component_Added` event to make sure that `SadComponents` get the applicable components?

**Comment by Chris3606** [comment]
Yes, this is precisely what the the original proposal suggested.

**Comment by fcheadle** [comment]
This change has been implemented in the latest version on main

**Comment by Chris3606** [comment]
My only remaining complaint is that we still have both `AddComponent`/helper functions on `RoguelikeEntity`, and the `AllComponents`.  I think we should only provide one or the other (and as stated previously my preference is toward keeping only `AllComponents`.  I think providing multiple ways to do identical things only confuses the interface which already relies on documentation as opposed to being self-documenting.

**Comment by Chris3606** [comment]
Similarly, regardless of which one we choose, [this code](https://github.com/thesadrogue/TheSadRogue.Integration/blob/f9bb3f08706d9928eae6a4f21ef64dc230a9e2d5/TheSadRogue.Integration/RogueLikeEntity.cs#L110) should be performed in `On_GoRogueComponentAdded`, not in `AddComponent`, to ensure that parent is set properly regardless of how the component is added.  There also needs to be a `On_GoRogueComponentRemoved` handler that sets the `Parent` to null.

**Comment by fcheadle** [comment]
Your concerns are now addressed in this PR: https://github.com/thesadrogue/TheSadRogue.Integration/pull/28
