### ISSUE TITLE
Proposal: Implement `IScreenObject` on `RoguelikeMap`

### ISSUE THREAD

**Issue by Chris3606** [thesadrogue/TheSadRogue.Integration#22]
Because of the restructure of SadConsole v9, I don't think we need to do this whole attach-to-surface map object system anymore. `RoguelikeMap` could explicitly implement `IScreenObject`, hiding all of the SadConsole aspects we choose, yet, still be able to directly add the map to the SadConsole object model.

This would enable easier code for the user:

```csharp
Map = GenerateMap();
PlayerCharacter = GeneratePlayerCharacter();
Map.AddEntity(PlayerCharacter);
GameHost.Instance.Screen = MapWindow;
```

And the `RoguelikeMap` could be implemented similar to:

```csharp
partial class RoguelikeMap : Map, IScreenObject
{
    private IScreenObject _screenObjectWrapper;

    // In RoguelikeMap.ScreenObject.cs
    FocusBehavior IScreenObject.FocusedMode { get => _screenObjectWrapper.FocusedMode; set => _screenObjectWrapper.FocusedMode = value; }
    Point IScreenObject.AbsolutePosition => _screenObjectWrapper.AbsolutePosition;
    ScreenObjectCollection IScreenObject.Children => _screenObjectWrapper.Children;
    
.... more props/events/etc
```

With the map having layers (unsure how many, terrain, entity? more?) each can possibly be added as a surface to the map as a child which automatically renders the layer. You would just need to expose a viewport (maybe map has that already) and forward that to each surface.

_Originally posted by @Thraka in https://github.com/thesadrogue/TheSadRogue.Integration/issues/4#issuecomment-755496111_

**Comment by Chris3606** [comment]
@Thraka  I think we may need to flesh out the code example in the proposal above, as I'm a little unclear on the intent...

But as I understand it, the proposal is to implement `IScreenObject` on `RoguelikeMap`, such that it has surfaces and entity renderers as screen surfaces, etc as children that render the map however is needed. then you just add the `RoguelikeMap` directly to the SadConsole object hierarchy to render it.  Is this correct?

My main concern with this is that is, the "map" is simply data; one map does not necessarily correspond to one place it is rendered.  It may be rendered at exactly one point on the screen (main game view), or could be rendered in some capacity at different points (two different views of the map, or a main map and a mini-map, for instance).  So one viewport and one method of rendering may not correspond to one `RoguelikeMap` object; the map is simply data, that could be rendered however many times in however many places is needed.  I'm not sure how to enable these situations if the map becomes its own renderer.

**Comment by Thraka** [comment]
I see what you're saying. I was thinking more about a single "render" of the map being the simple way to get a map in the game, and `IScreenObject` lets you just add the map somewhere.

This wont work with the entity renderer https://github.com/thesadrogue/TheSadRogue.Integration/blob/main/TheSadRogue.Integration/RogueLikeMap.cs#L80

The entity renderer doesn't allow itself to be added to multiple objects. This would have to be designed to create an entity renderer for each map renderer and make sure they're managed together. Also, only one renderer would still need to be the main renderer that processes `Update` on the entities. Actually that is a bad idea too. The map itself should be processing update on the entities.

We may just need a new entity renderer created to support this multiple views into a single map.

However, I don't feel that this scenario is probably that common. If you look at all of the different ascii and graphical roguelike games released, how many allow you to have multiple viewports of the same map or data displayed at the same time? Crafting the integration library around this concept just adds a ton of complexity.

**Comment by Chris3606** [comment]
I could be wrong, but since line 80 is adding a new renderer that was created two lines previous, I think it shouldn't ever attach the same renderer to multiple objects, so that part shouldn't be an issue.

Even if that's the case, though, the calling Update issue is a huge problem currently.  I must about I see no easy solution to this, as SadConsole has no way to know about the map directly in the current case.


> However, I don't feel that this scenario is probably that common
It's probably not, but completely ignoring that use case concerns me for a few reasons:
1. I believe the the previous integration library explicitly supported this
2. So far as I recall, it was asked about a couple times in help channels on discord
3. Writing rendering code is nontrivial; if the solution is "if you need that, write your own renderer", then what we're asking a user to do to don't support their use case is write code in multiple backends, implementing the appropriate SadConsole abstractions in each. The first person who gets that answer when they ask about a minimap is likely to be dissatisfied.

**Comment by Thraka** [comment]
Sorry, really when I say "Write your own entity renderer" I mean "entity manager". I'm always speaking in the context of a user (and this library) would never have to write any gamehost specific code which includes monogame/sfml rendering. 
😄

**Comment by Thraka** [comment]
https://github.com/thesadrogue/TheSadRogue.Integration/blob/main/TheSadRogue.Integration/RogueLikeMap.cs#L114 won't work if someone adds another entity renderer to the object. The class should keep track of the `Entities.Renderer` object it creates instead of only keeping track of the registered surface.

**Comment by Chris3606** [comment]
Agreed

**Comment by Chris3606** [comment]
After some discussions here and otherwise, I currently have the following tentative proposal:

- In the `TheSadRogue.Integration.Maps` namespace, create (names TBD/placeholder):
    - `RoguelikeMapBase`
    - `RoguelikeMap`
    - `AdvancedRoguelikeMap`

Each class serves the following role:
- **RoguelikeMapBase:** Abstract base class that is quite similar to what we have right now, except that `CreateRenderer`, `DisposeOfRenderer`, and perhaps the `Renderers` list are `protected` instead of public.
- **RoguelikeMap:** Intended for typical simple use case where you have a single view of the map that you would like to render.  Inherits from `RoguelikeMapBase`.  Has a private backing field `_renderer` that is created by a call to `CreateRenderer`.  Implements `IScreenObject` by forwarding any properties therein to `_renderer`.  Also exposes the viewport field from `_renderer` as a property.  EntityRenderer for the object will be configured with `DoEntityUpdate` on so update is taken care of
    - Purposefully implements `IScreenObject`, not `IScreenSurface`, to disallow the user changing the surface manually (which is catastrophic to renderer synchronization)
- **AdvancedRoguelikeMap:** Intended for use cases involving multiple renderers, where the above implementation is insufficient.  Inherits from `RoguelikeMapBase`.  Makes `CreateRenderer` and `DisposeOfRenderer` public, but makes sure that `EntityRenderer` instances attached do NOT have `DoEntityUpdate` set.  This class will also need some sort of component or property that calls `Update` on all entities, whether that means implementing `IScreenObject` as such, or simply having a component that must be added to the object heirarchy somewhere that calls it.

**Comment by Chris3606** [comment]
One additional caveat to the current proposal is that `GoRogue.GameFramework.Map` exposes a `GoRogueComponent` field, and since `IScreenObject` exposes `SadComponents` it may be wise to do a component-sync like `RoguelikeEntity` does here as well.

**Comment by fcheadle** [comment]
Why not just have a class, ___RogueLikeMap__, that exposes those methods as `virtual`? Would we even need an abstract base class?

**Comment by Chris3606** [comment]
Yes, because `RoguelikeMap` makes assumptions that it _must_ in and of itself be the _only_ renderer for the map.  So exposing those functions in both cases would be extremely error prone, as calling them would lead to catastrophe (double Update calls per frame, etc).   The functionality of those functions is the same in both concrete maps; the rules for the user being able to call them (or not) cannot be if the code is to remain safe.

**Comment by Chris3606** [comment]
Edit: @fcheadle _technically_ a single class would be possible, but it would lose a lot of convenience because a multi-renderer interface that (unlike the current implementation on main) makes proper guarantees about when Update, etc, are called, requires some less-than-intuitive behavior, when you're only thinking about it from the perspective of a single renderer.

@Thraka one thing about the current implementation, is that in `AdvancedRogueLikeMap`, which implements `IScreenObject` in the linked PR, has a position, although it renders nothing.  This is just a side effect of what all `IScreenObject` defines (because it includes a `Position` and rendering functions.  Additionally, since it currently uses a `ScreenObject` as the backing field, note that it can have children (which render relative to it) although the map doesn't actually render anything itself.  It _could_ lead to people attaching components to and `AdvancedRogueLikeMap` and then wondering why things are all messed up relative to their renderer; but at least this complexity is hidden in `RogueLikeMap` (and indeed adding such children is a useful feature in `RogueLikeMap`.

**Comment by Thraka** [comment]
> Thraka one thing about the current implementation, is that in `AdvancedRogueLikeMap`, which implements `IScreenObject` in the linked PR, has a position, although it renders nothing. This is just a side effect of what all `IScreenObject` defines (because it includes a `Position` and rendering functions). Additionally, since it currently uses a `ScreenObject` as the backing field, note that it can have children (which render relative to it) although the map doesn't actually render anything itself. It _could_ lead to people accidentally attaching children and/or components to an `AdvancedRogueLikeMap` and then wondering why things are all messed up relative to their renderer; but at least this complexity is hidden in `RogueLikeMap` (and indeed adding such children is a useful feature in `RogueLikeMap`).
> 
> The only thing I can think to do to fix the latter bit would be to implement `IScreenObject` only on `RogueLikeMap`, and have `AdvancedRogueLikeMap` simply provide an `IComponent EntityUpdater` component which the user is required to slot into their system somewhere.... But that feels more error-prone.

We can lock down the children easily, use `Children.IsLocked` when you create the backing screen object. This will throw an exception if someone tries to add a child.

Position is a bit tricky. We could hook the `map.PositionChanged` event and throw an exception letting the user know that moving the position of this object doesn't do anything and instead to "move" the map work with the renderers created via the method.

**Comment by Thraka** [comment]
@fcheadle For some clarification: I would like to have the map simple to use for a user. Not having to worry about generating renderers and attaching them to surfaces etc. I want a simple map that can just be created, parented to an object in SadConsole, and drawn on the screen. This is where people would start at. If they end up requiring the capability of drawing the map in multiple independent locations then they could use the advanced version.

**Comment by Chris3606** [comment]
> We can lock down the children easily

@Thraka agreed, though I'm split on whether or not we should.  It could actually be useful to do something like:
```
var map = new AdvancedRogueLikeMap(...);
map.Children.Add(map.CreateRenderer(...)
map.Children.Add(.map.CreateRenderer(..))
```

Where the two renderers have different positions, and then you just add the `map` object to your scene, and use its parent position to position the renderers as a group on screen.  It's not the only use for multiple renderers, but thinking about it further, I'm hesitant to advocate taking this away.
