### ISSUE TITLE
Determine whether to re-implement `Tiles` namespace from previous integration library

### ISSUE THREAD

**Issue by Chris3606** [thesadrogue/TheSadRogue.Integration#48]
The old integration library had a system implemented in Tiles which consisted of some addons to the basic map/object structure to support looking at terrain as if it was sets of flags.  We need to determine if we want to re-implement it in this version, and if we do which pieces.

It is also isolated enough that implementing it as a separate package may be a possibility.

**Comment by Thraka** [comment]
If it's from me long ago, it was a separate design. I don't know if it still fits. I would just give users one way of doing things.

**Comment by Chris3606** [comment]
Yeah I agree, I think if we keep what was in `Tiles` we should have it as a separate package if anything.  It's definitely not core to the integration piece.
