### ISSUE TITLE
New Generation Steps are somewhat dangerous

### ISSUE THREAD

**Issue by fcheadle** [thesadrogue/TheSadRogue.Integration#5]
Each of the new generation steps includes a line similar to the following:

`var map = context.GetFirstOrNew<ISettableGridView<bool>>(()=> new ArrayView<bool>(context.Width, context.Height));`

This is inherently unsafe, as there is no way to guarantee that there is only one component of this type on the GenerationContext.

The fix is to use tags, like how GoRogue uses them.

However, there is a possibility that the generation steps don't belong in the integration lib at all, and may move into the GoRogue repository. See [GoRogue #128](https://github.com/Chris3606/GoRogue/issues/218 )

**Comment by Chris3606** [comment]
I've got a few bugs I need to fix in GoRogue that will likely end up getting done before this, and I anticipate having reduced dev time for a few weeks at the end of January-beginning of Feburary timeframe.  Feel free to make some of the improvements in the integration library for the time being, and we can move it to GoRogue sometime after; that way it doesn't become a bottleneck.

**Comment by fcheadle** [comment]
TODO - `Rooms` in the `BackroomGenerationStep` should be private and retrievable through the `GetFirstOrNew<ISettableMapView<bool>>`. That will come after the rest of the PR.

**Comment by fcheadle** [comment]
I'm attempting to use the integration library in another project as a deeper test of the capabilities. I've added a tag to the generation steps and am getting them back via there tag - [example code](https://github.com/fcheadle/HomicideDetective/blob/d284844561d0589f9422a6e9775e960a267c057a/HomicideDetective.New/Program.cs#L47 ). 

Is this the way of making them safer?

**Comment by fcheadle** [comment]
They'll be safer when I delete them because they've moved to GoRogue in issue 218 over there.

**Comment by Chris3606** [comment]
See the linked issue; I think we could close this if we got a Draft PR that has the generation steps in their current state to GoRogue's repository; that way both the source and tracking issues are associated there.

**Comment by Chris3606** [comment]
Tracked via https://github.com/Chris3606/GoRogue/pull/222.  The steps will be removed from the integration lib in a subsequent PR, and future work will be tracked there.
