### ISSUE TITLE
RogueLikeMap is ghastly inefficient

### ISSUE THREAD

**Issue by fcheadle** [thesadrogue/TheSadRogue.Integration#9]
RogueLikeMap currently uses a RogueLikeEntity for every cell on the map - including terrain tiles.

Terrain Tiles typically don't need as much functionality as most entities, so we can achieve better memory and speed by creating a small class (such as RogueLikeCell) which inherits from GameObject and contains a ColoredGlyph, and then RogueLikeEntity can slightly change to incorporate this in a more elegant way.

**Comment by fcheadle** [comment]
Added RogueLikeCell.

**Comment by Chris3606** [comment]
Should be solved in #1 .
